version: "3.8"

services:
  webizly:
    build: . 
    container_name: mywebclass 
    pull_policy: always
    restart: always
    networks:
       - traefik
       - backend
    ports:
      - "80"
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.cosmic-connect.rule=Host(`www.cosmic-connect.org`) || Host(`cosmic-connect.org`)
      - traefik.http.routers.cosmic-connect.entrypoints=https
      - traefik.http.routers.cosmic-connect.tls=true
      - traefik.http.routers.cosmic-connect.tls.certresolver=simple-resolver
      - traefik.http.services.cosmic-connect.loadbalancer.server.port=80
networks:
  traefik:
      name: traefik
      external: true
  backend:
      external: true
